data:
  batch_size: 256
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: imagenet100
  num_workers: 10
  pin_mem: true
  root_path: datasets/
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  checkpoint_freq: 300
  folder: logs_IN100/in100-vitb-l2-pkt-chunks-ep600-seed0
  logging_frequency: 2
  output_file: oin100-pretrain-vitb-l2-pkt-chunks-ep600-seed0.out
  write_tag: jepa_in100
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
message: ViT-B/16 L2 + PKT chunks on IMAGENET100 seed 0
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 6
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  accumulate_grads_every: 4
  ema:
  - 0.996
  - 1.0
  epochs: 600
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  loss_function: L2_PKT_chunks
  lr: 0.001
  pkt_scale: 1.0
  start_lr: 0.0002
  variance_weight: 0.0
  warmup: 80
  weight_decay: 0.04
pkt:
  T_max: 200
  chunks_step: 256
  final_alpha: 0.0
  ref_alpha: 1.0
  start_alpha: 1.0
  use_pkt_scheduler: false
  warmup_steps_alpha: 100
