data:
  crop_size: 150
  num_classes: 10
  train_dataset_path: datasets/stl10/train_images
  val_dataset_path: datasets/stl10/val_images
  model_name: vit_base
  batch_size: 128
  patch_size: 15
  probe_checkpoints: true
  probe_prefix: jepa-stl
logging:
  log_dir: logs_STL/stl-l2-pkt-chunks-seed2/
  # pretrained_model_path: jepa_iic_l2-seed-43-latest.pth.tar # omit this, 1st try
  save_path: classifiers/jepa-stl-l2-seed2-classifier-pretrained-vitb
  checkpoint_freq: 1000
  log_file: stl-stats-l2-pkt-chunks-seed2.csv # the .csv file
  eval_output: ocls-jepa-stl-l2-pkt-chunks-seed2.out # the .out file
optimization:
  lr: 0.001
  epochs: 100
  use_last_n_blocks: 1 # not yet supported
  use_normalization: false # use layer_norm and dropout layer
meta:
  device: cuda:0
message: "Multi classification back to back"
multi_probing:
  # - logs_STL/stl-l2-pkt-chunks-seed0
  # - logs_STL/stl-l2-pkt-chunks-seed2
  # - logs_STL/stl-l2-seed0
  - logs_STL/stl-l2-pkt-chunks-seed1-NEW