data:
  crop_size: 224
  num_classes: 1000
  train_dataset_path: datasets/imagenet/ILSVRC/Data/CLS-LOC/train  # datasets/imagenet/train
  val_dataset_path: datasets/imagenet/ILSVRC/Data/CLS-LOC/val
  model_name: vit_base
  batch_size: 1024
  patch_size: 16
  probe_checkpoints: true
  probe_prefix: jepa-in1k
  num_workers: 16
  pin_mem: True
  val_label_csv: /home/lazarosg/ijepa/datasets/imagenet/LOC_val_solution.csv
logging:
  log_dir: logs_IN1K/in1k-vitb16-l2-pkt-chunks-ep100-bs256-w20-unscaled/
  # pretrained_model_path: jepa_iic_l2-seed-43-latest.pth.tar # omit this, 1st try
  save_path: classifiers/jepa-stl-l2-ep300-seed0-classifier-pretrained-vitb
  checkpoint_freq: 1000
  log_file: stats-in1k-l2-ep100-seed0.csv # the .csv file
  eval_output: ocls-jepa-in1k-l2-ep100-seed0.out # the .out file
optimization:
  lr: 0.001
  epochs: 200
  use_last_n_blocks: 1 # not yet supported
  use_normalization: false # use layer_norm and dropout layer
meta:
  device: cuda:0
# message: "Multi classification back to back"
multi_probing:
  # - logs_IN100_vits/in100-vits16-l2-ep300-bs448
  # - logs_IN1K/in1k-vitb16-l2-pkt-chunks-ep100-bs256-w20-unscaled
  - logs_IN1K/in1k-vitb16-l2-pkt-chunks-ep300-bs256
    
# nohup /opt/conda/envs/ijepa/bin/python pmulti-linear-probing.py --fname cls_configs/cls-in1k-multi-pkt.yaml &> logs_IN1K/in1k-vitb16-l2-pkt-chunks-ep100-bs256-w20-unscaled/oin1k-DOWNSTREAM_TASK.out &
