data:
  crop_size: 150
  num_classes: 6
  train_dataset_path: datasets/intel-image-classification/train
  val_dataset_path: datasets/intel-image-classification/test
  model_name: vit_base
  batch_size: 128
  patch_size: 15
  probe_checkpoints: true
  probe_prefix: jepa-iic-PKT
logging:
  log_dir: logs_PKT_full/iic-train-PKT-seed15
  pretrained_model_path: jepa_iic_PKT_seed-0-latest.pth.tar
  save_path: classifiers/jepa-iic-PKT-seed-10-classifier-pretrained-vitb-normalized
  checkpoint_freq: 1000
  log_file: iic-stats-pktfull # the .csv file
  eval_output: ocls-jepa-iic-pktfull # the .out file
  message: "Random backbone ViT-B"
optimization:
  lr: 0.001
  epochs: 200
  use_last_n_blocks: 1 # not yet supported
  use_normalization: true # use layer_norm and dropout layer
meta:
  device: cuda:1