data:
  batch_size: 64
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 150
  image_folder: intel-image-classification/
  num_workers: 0
  pin_mem: true
  root_path: datasets
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: logs_PKT/iic-train-PKT-seed-1/
  write_tag: jepa-iic-PKT
  checkpoint_freq: 100 # new addition
  logging_frequency: 1 # defaults to 3, more concise logs
  output_file: oiic-pretrain-PKT-seed-1-evalluaion.out
mask:
  allow_overlap: false
  aspect_ratio: 
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 1
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 15
  pred_mask_scale:
  - 0.15                    # default: 0.15
  - 0.2                     # default: 0.2
meta:
  copy_data: false          # default: false
  load_checkpoint: true
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: jepa_iic_PKT-ep500.pth.tar     # default: null
  use_bfloat16: false       # default: true
  
optimization:
  ema:
  - 0.996                   # default: 0.996
  - 1.0                     # default: 1.
  epochs: 500
  final_lr: 1.0e-06         # default: 1.0e-06
  final_weight_decay: 0.4   # default: 0.4
  ipe_scale: 1.0
  lr: 0.001                 # default: 1e-3
  start_lr: 0.0002          # default: 2e-4
  warmup: 40
  weight_decay: 0.04        # default: 0.04
  loss_function: PKT
  # message: "third try at full PKT for reproducibility"
  evaluate: True           # get similarity distributions?
