data:
  batch_size: 64
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 150
  image_folder: intel-image-classification/
  num_workers: 10
  pin_mem: true
  root_path: datasets
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: logs/iic-train-tiny/
  write_tag: jepa_iic_tiny
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 1
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 15
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_tiny
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996                   # default: 0.996
  - 1.0
  epochs: 500
  final_lr: 1.0e-06         # default: 1.0e-06
  final_weight_decay: 0.4   # default: 0.4
  ipe_scale: 1.0
  lr: 0.001                 # default: 1e-3
  start_lr: 0.0002          # default: 2e-4
  warmup: 40
  weight_decay: 0.04        # default: 0.04
