data:
  batch_size: 384
  color_jitter_strength: 0.0
  crop_scale: 
  - 0.3
  - 1.0
  crop_size: 224
  image_folder: imagenet100
  num_workers: 10
  pin_mem: true
  root_path: datasets/
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: logs_IN100/in100-vitb16-l2-pkt-chunks-ep300-bs384
  write_tag: jepa-in100
  checkpoint_freq: 150 # new addition
  logging_frequency: 3 # defaults to 3, for more concise logs
  output_file: oin100-pretrain-vitb-l2-pkt-chunks-ep300-bs384-seed0.out
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 16
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 6
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 300
  final_lr: 1.0e-06         # default: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.001              # default: 0.001
  start_lr: 0.0002        # default: 0.0002
  warmup: 40                # default: 40
  weight_decay: 0.04
  loss_function: L2_PKT_chunks
  pkt_scale: 1.0e+0   
  variance_weight: 0.0
  accumulate_grads_every: 1
pkt:
  use_pkt_scheduler: false
  start_alpha: 1.
  warmup_steps_alpha: 100
  ref_alpha: 1.
  T_max: 200
  final_alpha: 0.
  chunks_step: 256
message: "ViT-B/16 L2 on IMAGENET100 seed 0 batch size 384"