data:
  batch_size: 60
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 150
  image_folder: intel-image-classification/
  num_workers: 10
  pin_mem: true
  root_path: datasets
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  checkpoint_freq: 100
  folder: logs_PKT_chunks/iic-train-l2-pkt-chunks-seed2
  logging_frequency: 2
  output_file: oiic-pretrain-l2-seed2.out
  write_tag: jepa-iic-l2-seed2
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 1
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 15
  pred_mask_scale:
  - 0.15
  - 0.2
message: L2 + PKT chunks seed 2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: false
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 500
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  loss_function: L2_PKT_chunks
  lr: 0.001
  pkt_scale: 1.0
  start_lr: 0.0002
  variance_weight: 0.0
  warmup: 40
  weight_decay: 0.04
pkt:
  T_max: 200
  final_alpha: 0.0
  ref_alpha: 1.0
  start_alpha: 1.0
  use_pkt_scheduler: false
  warmup_steps_alpha: 100
